source 'https://cdn.cocoapods.org/'
source 'https://github.com/changjianfeishui/mht-specs'

use_frameworks!

platform :ios, '13.0'

target 'MHTPublicParameters_Example' do
  pod 'MHTPublicParameters', :path => '../'

  target 'MHTPublicParameters_Tests' do
    inherit! :search_paths

    
  end
end
